config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'articles', to: 'articles#index'
  get 'articles', to: 'articles#recent'
  get 'articles', to: 'pages#home'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :desription, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was saved successfully!"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  # def show 
  # end

  def destroy
    @article.destroy
    flash[:notice] = "Blog was deleted"
    redirect_to articles_path
  end

  def recent
    @articles = Article.all
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :desription)
    end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @articles = Article.all
  end

  def about
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="new-article_container form_container flex-center flex-vert half-width">
  <%= form_for @article do |f| %>

    <% if @article.errors.any? %>
      <p class="flex-center form_element">
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li> <%=msg%> </li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <p class="flex-center form_element">
      <%= f.label :title, "Blog Title" %>
      <%= f.text_field :title %>
    </p>

    <p class="flex-center form_element">
      <%= f.label :desription, "Description" %>
      <%= f.text_area :desription %>
    </p>

    <p >
      <%= f.submit "Submit", disable_with: 'Submiting...' %>
    </p>
    <p class="style_link">
      <%= link_to "Back To Blogs",  articles_path %>
    </p>

  <% end %>
</div>

app/views/articles/_recent.html.erb
<div>
  <%  @articles.each do |article| %>
    <div class="blogs_blog bg1 border">
      <div class="blog_container_txt flex-vert">
        <h3 class="c3">
          <%= article.title %> 
        </h3>
        <p class="c3">
          <%= article.desription %> 
        </p>
      </div>
      <div class="blog_container_btns flex-center style_link">
        <%= link_to 'Show', article_path(article) %> 
        <%= link_to 'Edit', edit_article_path(article) %> 
        <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %> 
      </div>
    </div>
  <%end%>
</div>

app/views/articles/edit.html.erb
<%= render 'partials/header.html.erb', {:banner => 'Edit', :showName => true} %>
<%= render 'form' %>  

app/views/articles/index.html.erb
<%= render 'partials/header.html.erb', {:banner => 'blog'} %>
<% @articles.each do |article| %>
  <div class="">
  
    <div class="card text-center ">
      <div class="card-body flex-center flex-vert">
        <h5 class="card-title"><%= article.title%> </h5>
        <p class="card-text"><%= article.desription%> </p>
        <%= link_to 'read', article_path(article), class: "btn btn-primary btn-lg btn_hov" %> 
      </div>

      <div class="card-footer text-muted">
        <%= article.created_at%>
      </div>
      
    </div>
  
  </div>
<%end%>

<p class="style_link blogs_container_create">
  <%= link_to "Create new article", new_article_path %>
</p>

app/views/articles/new.html.erb
<%= render 'partials/header.html.erb', {:banner => 'Create A New Blog'} %>
<%= render 'form' %>

app/views/articles/show.html.erb
<%= render 'partials/header.html.erb', {:banner => '', :showName => true} %>

<div class="flex-center flex-vert style_link">
  <h2>Let me tell you something...</h2>
  <p><%= @article.desription %></p>
  <%= link_to "Back To Blogs",  articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ellis Sinclair</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application.css'%>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'partials/header.html.erb', {:banner => 'about ellis'} %>

<div class="about_section ">
  <div class="row">
    <div class="col-md-3 col-12 flex about_pic">
      <div class="bio_pic_bg"></div>
      <%= image_tag 'temp-bio-pic.jpg', class: 'm_to_right' %>
    </div>
    <div class="col-md-8 col-12 about_text">

      <p><span class="t_bold">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum nihil, ipsum esse, pariatur magni, excepturi accusantium iusto commodi ex beatae fuga?</span> Alias doloremque suscipit facilis, nesciunt fugit magnam blanditiis quas. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni dolorem fugit sapiente consequuntur atque modi, eveniet, excepturi perspiciatis porro adipisci dicta, minus odio mollitia. Corrupti ducimus explicabo ratione delectus nesciunt.

      <br><br>

      Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis cupiditate quia ipsam nesciunt quae, facilis, quod voluptatum porro ratione voluptas esse nam ad inventore dolorum itaque ab corporis ipsum quasi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde beatae perspiciatis velit fugit laborum? Facilis, accusamus incidunt, sapiente dolor maxime dolores expedita voluptatibus tenetur perspiciatis odio dignissimos voluptatem, et rem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum vel dolores necessitatibus totam? Deserunt impedit aut totam tempora corporis ea consequatur explicabo vero aperiam, ab, soluta architecto, nobis voluptatum labore.
      <br><br>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis cupiditate quia ipsam nesciunt quae, facilis, quod voluptatum porro ratione voluptas esse nam ad inventore dolorum itaque ab corporis ipsum quasi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde beatae perspiciatis velit fugit laborum? Facilis, accusamus incidunt, sapiente dolor maxime dolores expedita voluptatibus tenetur perspiciatis odio dignissimos voluptatem, et rem. Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum vel dolores necessitatibus totam? Deserunt impedit aut totam tempora corporis ea consequatur explicabo vero aperiam, ab, soluta architecto, nobis voluptatum labore.</p>

    </div>
  </div>

</div>


<%= render 'partials/footer.html.erb' %>

app/views/pages/home.html.erb
<!== ******* >
<!== NAV BAR >
<!== ******* >

<%= render 'partials/header.html.erb', {:banner => 'ellis sinclair'} %>

<!== ************ >
<!== BOOK SECTION >
<!== ************ >

  <div class="bg2 s1book">
    <div class=" section book_section bg_white flex-center">
        <div class="row flex-center">
          <div class="col-sm-12 col-md-4  home_book_book flex">
            <%= image_tag "book-cover-arcadia.jpeg" %>   
          </div>
          <div class="col-sm-12 col-md-8 home_book_desc flex-center flex-vert c1">
            <div class="flex-center flex-vert container_title">
              <h2 class="bg_white">Arcadia</h2>
              <div class="under_line_1 bg5"></div>
            </div>
            <p>Arcadia was a small town, nestled in the countryside, hidden from the bustling life of the metropolis Athens to the north. It was once an idyllic village of hills and apple orchards, a place to settle down, a place where children and families could grow.</p>
            <p>One abandoned home, a monument of history and decay, cast its long shadow across the village and hidden forces from darker places plague the residents in their attempt to reclaim the town. Our story begins with a young boy named Vincent, visiting Arcadia after the death of his grandmother. He finds himself as the most recent quarry in a struggle to regain the town spanning the generations of those who came before him.</p>
            <a class="btn btn-primary btn-lg icon_btn btn_hov" target="_blank" href="https://www.amazon.com/Arcadia-Ellis-Sinclair/dp/1612969178" role="button"> <span class="c_accent">ORDER</span>NOW   <i class="fab fa-amazon fa-sm"></i></div></a>
          </div>
        </div>
    </div>
  </div>


<!== *************** >
<!== PATREON SECTION >
<!== *************** >

  <div class="bg_white s2patreon">
    <div class="section patreon bg2 flex-center flex-vert">
      <div class="row flex-center flex-vert">

        <h1> <span class="c_accent">Subscribe</span> To My Patreon</h1>
        <p>Like my writing? Support me writing more by subscribing to my patreon!</p>
        <div class="under_line_1 bg4"></div>
        <i class="fab fa-patreon fa-10x"></i>
        <a class="btn btn-primary btn-lg btn_hov" href="#" role="button">SUBSCRIBE</a>

      </div>
    </div>
  </div>


<!== ************* >
<!== ABOUT SECTION >
<!== ************* >


  <div class="bg2 s3about">
    <div class="section home_about_container bg_white flex-center flex-vert">
      <div class="row flex">

        <div class="col-md-5 col-12 flex-center mobile_bio_pic">
            <%= image_tag 'temp-bio-pic.jpg' %>
        </div>
        
        <div class="col-md-7 col-12 flex-center flex-vert">
          <div class="flex-center flex-vert container_title_2 m_to_right">
            <h2 class="m_to_right bg_white"> <span class="">Ellis</span>  Sinclair</h2>
            <div class="under_line_2 bg5 "></div>
          </div>

          <p class="t_right">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatem dolores perspiciatis quasi praesentium earum fugiat quae laudantium obcaecati! Eius perspiciatis a laborum accusamus molestias rem optio voluptas distinctio maiores tempora.</p>
          
          <div class="flex m_to_right">
            <div class="about_icons flex-center">
              <div class="ic flex-center">
                <i class="fab fa-facebook-square fa-2x"></i>
              </div>
              <div class="ic flex-center">
                <i class="fab fa-instagram fa-2x"></i>
              </div>
              <div class="ic flex-center">
                <i class="fab fa-amazon fa-2x"></i>
              </div>
            </div>
            <a class="m_to_right btn btn-primary btn-lg btn_hov" href='<%= about_path %>' role="button"><span class="c_accent">MoreAbout</span>Ellis</a>   
          </div>

        </div>

        <div class="col-md-5 col-12 flex-center desktop_bio_pic">
            <%= image_tag 'temp-bio-pic.jpg' %>
        </div>

      </div>
    </div>
  </div>


<!== ************ >
<!== BLOG SECTION >
<!== ************ >

<%
=begin%>
 <div class="blog_spacer bg2"></div> 
<%
=end%>

<div class="section home_blog_container bg1 flex-center flex-vert">
  <div class="flex-center flex-vert container_title">
    <h2> <span class="">Latest</span> Blogs</h2>
    <div class="under_line_1 bg5"></div>
  </div>
  <div class="blogs full_width">
    <%= render 'partials/recentBlogs.html.erb' %>
  </div>
  <%
=begin%>
 <p class="">Say a few things about your blog here</p> 
<%
=end%>
  <div class="flex">
    <a class="btn btn-primary btn-lg btn_hov " href='<%= articles_path %>' role="button"> <span class="c_accent">MORE</span>BLOGS</a>
    <a class="btn btn-primary btn-lg btn_hov" href="#" role="button">SUBSCRIBE</a>
  </div>
</div>


<!== ****** >
<!== FOOTER >
<!== ****** >

<%= render 'partials/footer.html.erb' %>

app/views/partials/_footer.html.erb
<div class="footer flex-center bg2">
  
  <div class="row">

    <div class="col-md-4 col-12 amazon">
      <a class="btn btn-primary btn-lg icon_btn btn_hov" target="_blank" href="https://www.amazon.com/Arcadia-Ellis-Sinclair/dp/1612969178" role="button">ORDER ARCADIA NOW   <i class="fab c_accent fa-amazon fa-sm"></i></a>
    </div>

    <div class="col-md-4 col-12 f_patreon">
      <a class="btn btn-primary btn-lg icon_btn btn_hov" target="_blank" href="https://www.amazon.com/Arcadia-Ellis-Sinclair/dp/1612969178" role="button">CHECK OUT PATREON   <i class="fab c_accent fa-patreon fa-sm"></i></a>
    </div>

    <div class="col-md-4 col-12 contact">
      <a class="btn btn-primary btn-lg icon_btn btn_hov" target="_blank" href="https://www.amazon.com/Arcadia-Ellis-Sinclair/dp/1612969178" role="button">CONTACT ELLIS SINCLAIR   <i class="fas c_accent fa-envelope fa-sm"></i></a>
    </div>

    <div class="col-md-12 col-12 flex-center flex-vert m_to_bottom">
      <div class="line bg1"></div>
      <p class=" c_white">Website developed & maintained by Bryan Jastrzembski</p>
    </div>

  </div>
</div>

app/views/partials/_header.html.erb
<div class="header_container flex-center  bg1">
      <h1 class="c1">
        <%= banner %> 
          <% if local_assigns.has_key? :showName %>
            <%= @article.title %>
          <% end %>
      </h1>
</div>
<nav class="navbar sticky-top navbar bg1">
  <div class="navbar_container bg1">
    <ul class="flex">
      <li><%= link_to  "home", root_path %></li>
      <li><%= link_to  "books", about_path %></li>
      <li><%= link_to  "blog", articles_path %></li>
      <li><%= link_to  "about", about_path %></li>
    </ul>
    
    <div class="navbar_social flex-center">
      <div class="ic flex-center">
        <i class="fab fa-facebook-square fa-lg"></i>
      </div>
      <div class="ic flex-center">
        <i class="fab fa-instagram fa-lg"></i>
      </div>
      <div class="ic flex-center">
        <i class="fab fa-amazon fa-lg"></i>
      </div>
      <div class="ic flex-center">
        <i class="fab fa-patreon fa-lg"></i>
      </div>
    </div>
  </div> 
</nav>

app/views/partials/_recentBlogs.html.erb
<div class="container-fluid blogs_recent_container">

    <div class="row">
      <% @articles.each do |article| %>
        <div class="col-lg-3 col-md-6 col-sm-12 col-12">
          <div class="card_container flex flex-center">
            <div class="card_top flex flex-center wid_full" id="top">
              <div class="card_top_pic ab wid_full hei_full">
              </div>  
              <div class="card_top_desc flex flex-center ab wid_full hei_full">
                <%= article.desription %>
              </div>
              <div class="card_top_btns flex ab wid_full">
                <%= link_to 'read', article_path(article), class: "ab wid_full flex-center", data: {icon: 'info', mini: 'true', role: 'button'} %>
              </div>    
            </div>
            <div class="card_bottom wid_full bg1 flex flex-center">
              <p><span class="p1"><%= article.title %></p>
            </div>
          </div>
        </div>
      <%end%>
    </div>

</div>